meta_name: "Game of Codes"
meta_title: "Game of Codes - Fun coding!"
meta_description: "Introduction to coding in a fun and simple way!"
meta_image: "https://res.cloudinary.com/ddpxdkwin/image/upload/v1694187880/Untitled-13_t5lwy5.png" # should exist in `app/assets/images/`
