meta_name: "Game of Codes"
meta_title: "Game of Codes - Fun code learning!"
meta_description: "Introduction to coding in a fun and simple way!"
meta_image: "Game-of-Codes-Index.png" # should exist in `app/assets/images/`
