meta_name: "Game of Codes"
meta_title: "Game of Codes - Fun coding!"
meta_description: "Introduction to coding in a fun and simple way!"
meta_image: "Game-of-Codes-dreamteam.png" # should exist in `app/assets/images/`
